# Ga4 q8 & 9

**User**: carlton
**URL**: [https://discourse.onlinedegree.iitm.ac.in/t/ga4-q8-9/153339/3](https://discourse.onlinedegree.iitm.ac.in/t/ga4-q8-9/153339/3)

Hi Pradeep,

The error is in the connection string (the clue is in the error in your screenshot: Unknown database)

Try this instead:

> engine = sa.create\_engine (“mysql+pymysql://guest:relational@db.relational-data.org/restbase”)

The rest looks okay, but a word of caution, your query is also not the right query for the question.

Kind regards
